version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "CODEBUILD_SRC_DIR=$CODEBUILD_SRC_DIR"
      - ls -la $CODEBUILD_SRC_DIR
      - cd $CODEBUILD_SRC_DIR/BloodDonationSupportSystemBE && npm ci

  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR/BloodDonationSupportSystemBE && npm run lint || true

  build:
    commands:
      - echo "Building..."
      - cd $CODEBUILD_SRC_DIR/BloodDonationSupportSystemBE && npm run build
      - cp $CODEBUILD_SRC_DIR/BloodDonationSupportSystemBE/package.json $CODEBUILD_SRC_DIR/BloodDonationSupportSystemBE/dist/
      - cd $CODEBUILD_SRC_DIR/BloodDonationSupportSystemBE/dist && npm install --production --ignore-scripts
      - cd $CODEBUILD_SRC_DIR/BloodDonationSupportSystemBE/dist && zip -r $CODEBUILD_SRC_DIR/deployment-package.zip .

  post_build:
    commands:
      - echo "Deploying to Lambda..."
      - aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://$CODEBUILD_SRC_DIR/deployment-package.zip
      - echo "Waiting for Lambda update to complete..."
      - aws lambda wait function-updated --function-name $LAMBDA_FUNCTION_NAME
      - aws lambda update-function-configuration --function-name $LAMBDA_FUNCTION_NAME --handler src/lambda.handler
      - echo "Done!"

artifacts:
  files:
    - deployment-package.zip
  base-directory: $CODEBUILD_SRC_DIR

cache:
  paths:
    - BloodDonationSupportSystemBE/node_modules/**/*
