version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Navigating to backend directory..."
      - cd BloodDonationSupportSystemBE
      - echo "Installing dependencies..."
      - npm ci

  pre_build:
    commands:
      - cd BloodDonationSupportSystemBE
      - echo "Running linting..."
      - npm run lint || true
      - echo "Pre-build completed"

  build:
    commands:
      - cd BloodDonationSupportSystemBE
      - echo "Building the application..."
      - npm run build
      - echo "Creating deployment package..."
      - cp package.json dist/
      - cd dist && npm install --production --ignore-scripts
      - zip -r ../deployment-package.zip .
      - cd ..

  post_build:
    commands:
      - cd BloodDonationSupportSystemBE
      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://deployment-package.zip
      - echo "Updating Lambda handler configuration..."
      - aws lambda update-function-configuration --function-name $LAMBDA_FUNCTION_NAME --handler src/lambda.handler
      - echo "Deployment completed successfully!"

artifacts:
  files:
    - BloodDonationSupportSystemBE/deployment-package.zip
  discard-paths: yes

cache:
  paths:
    - BloodDonationSupportSystemBE/node_modules/**/*
