version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Current directory:" && pwd
      - echo "Listing files:" && ls -la
      - echo "Installing dependencies..."
      - cd BloodDonationSupportSystemBE && npm ci

  pre_build:
    commands:
      - echo "Running linting..."
      - cd BloodDonationSupportSystemBE && npm run lint || true

  build:
    commands:
      - echo "Current directory:" && pwd
      - echo "Listing files:" && ls -la
      - echo "Building the application..."
      - cd BloodDonationSupportSystemBE && npm run build
      - echo "Creating deployment package..."
      - cp BloodDonationSupportSystemBE/package.json BloodDonationSupportSystemBE/dist/
      - cd BloodDonationSupportSystemBE/dist && npm install --production --ignore-scripts
      - cd BloodDonationSupportSystemBE/dist && zip -r ../deployment-package.zip .
      - echo "Listing deployment package:" && ls -la BloodDonationSupportSystemBE/

  post_build:
    commands:
      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://BloodDonationSupportSystemBE/deployment-package.zip
      - aws lambda update-function-configuration --function-name $LAMBDA_FUNCTION_NAME --handler src/lambda.handler
      - echo "Deployment completed!"

artifacts:
  files:
    - BloodDonationSupportSystemBE/deployment-package.zip
  discard-paths: yes

cache:
  paths:
    - BloodDonationSupportSystemBE/node_modules/**/*
