export const USERS_MESSAGES = {
  VALIDATION_ERROR: 'Validation Error',
  NAME_IS_REQUIRED: 'Name is required',
  NAME_MUST_BE_STRING: 'Name must be string',
  NAME_LENGTH_MUST_BE_BETWEEN_1_100: `Name's length must be between 1 and 100`,
  EMAIL_IS_REQUIRED: 'Email is required',
  EMAIL_IS_INVALID: 'Email is invalid',
  EMAIL_HAS_BEEN_USED: 'Email has been used',
  PASSWORD_IS_REQUIRED: 'Password is required',
  PASSWORD_MUST_BE_STRING: 'Password must be string',
  PASSWORD_LENGTH_IS_BETWEEN_8_50: `Password's length must be between 8 and 50`,
  PASSWORD_MUST_BE_STRONG: 'Password must be have 1 lower case, 1 upper case, 1 number, 1 symbol',
  CONFIRM_PASSWORD_IS_REQUIRED: 'Confirm Password is required',
  CONFIRM_PASSWORD_MUST_BE_STRING: 'Confirm Password must be string',
  CONFIRM_PASSWORD_LENGTH_BETWEEN_8_50: `Confirm Password's length between 8 and 50`,
  CONFIRM_PASSWORD_MUST_BE_STRONG: 'Confirm Password must be have 1 lower case, 1 upper case, 1 number, 1 symbol',
  CONFIRM_PASSWORD_MUST_BE_SAME_AS_PASSWORD: `Confirm_Password doesn't match password`,
  EMAIL_OR_PASSWORD_IS_INCORRECT: 'Email or Password is incorrect',
  LOGIN_SUCCESS: 'Login successful',
  LOGOUT_SUCCESS: 'Logout successful',
  REGISTER_SUCCESS: 'Register successful',
  ACCESS_TOKEN_IS_REQUIRED: 'Access Token is required',
  REFRESH_TOKEN_IS_REQUIRED: 'Refresh Token is required',
  REFRESH_TOKEN_IS_INVALID: 'Refresh Token is invalid',
  EMAIL_VERIFY_TOKEN_IS_REQUIRED: 'Email verify token is required',
  EMAIL_VERIFY_TOKEN_IS_INVALID: 'Email verify token is invalid',
  EMAIL_VERIFY_SUCCESS: 'Email verify successful',
  EMAIL_HAS_BEEN_VERIFIED: 'Email has been verify',
  USER_NOT_FOUND: 'User not found',
  ACCOUNT_HAS_BEEN_BANNED: 'Account has been banned',
  RESEND_EMAIL_SUCCESS: 'Resend email verify successful',
  CHECK_EMAIL_TO_RESET_PASSWORD: 'Check email to reset password',
  FORGOT_PASSWORD_TOKEN_IS_REQUIRED: 'Forgot password token is required',
  FORGOT_PASSWORD_TOKEN_IS_INVALID: 'Forgot password token is invalid',
  VERIFY_FORGOT_PASSWORD_TOKEN_SUCCESS: 'Verify forgot password token susccessful',
  RESET_PASSWORD_SUCCESS: 'Reset password successful',
  GET_ME_SUCCESS: 'Get me successful',
  IMAGE_URL_MUST_BE_A_STRING: 'Image url must be a string',
  IMAGE_URL_LENGTH_MUST_BE_LESS_THAN_400: 'Image url length must be less than 400',
  BIO_MUST_BE_A_STRING: 'Bio must be a string',
  BIO_LENGTH_MUST_BE_LESS_THAN_200: 'Bio length bust me less than 200',
  LOCATION_MUST_BE_A_STRING: 'Location must be a string',
  LOCATION_LENGTH_MUST_BE_LESS_THAN_200: 'Location length must be less than 200',
  WEBSITE_MUST_BE_A_STRING: 'Website must be a string',
  WEBSITE_LENGTH_MUST_BE_LESS_THAN_200: 'Website length must be less than 200',
  USERNAME_MUST_BE_A_STRING: 'Username must be a string',
  USERNAME_LENGTH_MUST_BE_LESS_THAN_50: 'Username length must be less than 50',
  UPDATE_PROFILE_SUCCESS: 'Update profile success',
  USER_NOT_VERIFIED: 'User not verified',
  USERNAME_ALREADY_EXISTS: 'Username already exists',
  USERNAME_IS_INVALID:
    'Username must be a string and length must be 4 - 15, and contain only letters, numbers, and underscores, not only numbers',
  CHANGE_PASSWORD_SUCCESS: 'Change password successful',
  REFRESH_TOKEN_SUCCESS: 'Refresh token successful',
  FILE_NOT_FOUND: 'File not found'
} as const //để k ai chỉnh đc
